"""Init multi-schema architecture

Revision ID: 344690fada1b
Revises: 
Create Date: 2026-09-01 12:56:30.490311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '344690fada1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('fluid_type', sa.String(length=50), nullable=False),
    sa.Column('pressure_threshold_kpa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vibration_threshold_mm_s', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('branding_display_name', sa.String(length=200), nullable=True),
    sa.Column('branding_primary_color', sa.String(length=20), nullable=True),
    sa.Column('branding_logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_tenant_slug'), 'tenant', ['slug'], unique=True, schema='master')
    op.create_table('model_metric',
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('dataset_split', sa.String(length=20), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('confusion_matrix', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_model_metric_evaluated_at'), 'model_metric', ['evaluated_at'], unique=False, schema='master')
    op.create_index(op.f('ix_master_model_metric_model_name'), 'model_metric', ['model_name'], unique=False, schema='master')
    op.create_index(op.f('ix_master_model_metric_tenant_id'), 'model_metric', ['tenant_id'], unique=False, schema='master')
    op.create_table('station',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('commissioned_on', sa.Date(), nullable=True),
    sa.Column('throughput_capacity_m3_per_day', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_station_code'), 'station', ['code'], unique=False, schema='master')
    op.create_index(op.f('ix_master_station_tenant_id'), 'station', ['tenant_id'], unique=False, schema='master')
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PLANNER', 'TECHNICIAN', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    schema='master'
    )
    op.create_index(op.f('ix_master_user_email'), 'user', ['email'], unique=False, schema='master')
    op.create_index(op.f('ix_master_user_tenant_id'), 'user', ['tenant_id'], unique=False, schema='master')
    op.create_table('regional_risk',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['master.station.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_regional_risk_station_id'), 'regional_risk', ['station_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_regional_risk_tenant_id'), 'regional_risk', ['tenant_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_regional_risk_timestamp'), 'regional_risk', ['timestamp'], unique=False, schema='bronze')
    op.create_table('weather_api',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['master.station.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_weather_api_station_id'), 'weather_api', ['station_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_weather_api_tenant_id'), 'weather_api', ['tenant_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_weather_api_timestamp'), 'weather_api', ['timestamp'], unique=False, schema='bronze')
    op.create_table('pump',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('tag_number', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model_number', sa.String(length=120), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('design_life_years', sa.Integer(), nullable=True),
    sa.Column('last_overhaul_date', sa.Date(), nullable=True),
    sa.Column('prior_intervention_count', sa.Integer(), nullable=False),
    sa.Column('rated_flow_m3_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rated_pressure_kpa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPERATIONAL', 'MAINTENANCE', 'STANDBY', 'DECOMMISSIONED', name='pump_status'), nullable=False),
    sa.Column('commissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['master.station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_pump_station_id'), 'pump', ['station_id'], unique=False, schema='master')
    op.create_index(op.f('ix_master_pump_tag_number'), 'pump', ['tag_number'], unique=False, schema='master')
    op.create_index(op.f('ix_master_pump_tenant_id'), 'pump', ['tenant_id'], unique=False, schema='master')
    op.create_table('regional_risk_score',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('composite_risk_score', sa.Float(), nullable=False),
    sa.Column('incident_count_30d', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['master.station.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='silver'
    )
    op.create_index(op.f('ix_silver_regional_risk_score_station_id'), 'regional_risk_score', ['station_id'], unique=False, schema='silver')
    op.create_index(op.f('ix_silver_regional_risk_score_tenant_id'), 'regional_risk_score', ['tenant_id'], unique=False, schema='silver')
    op.create_index(op.f('ix_silver_regional_risk_score_timestamp'), 'regional_risk_score', ['timestamp'], unique=False, schema='silver')
    op.create_table('weather_reading',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('wind_speed_m_s', sa.Float(), nullable=False),
    sa.Column('humidity_percent', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['master.station.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='silver'
    )
    op.create_index(op.f('ix_silver_weather_reading_station_id'), 'weather_reading', ['station_id'], unique=False, schema='silver')
    op.create_index(op.f('ix_silver_weather_reading_tenant_id'), 'weather_reading', ['tenant_id'], unique=False, schema='silver')
    op.create_index(op.f('ix_silver_weather_reading_timestamp'), 'weather_reading', ['timestamp'], unique=False, schema='silver')
    op.create_table('pump_telemetry',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('vibration_axial_mm_s', sa.Float(), nullable=False),
    sa.Column('vibration_radial_mm_s', sa.Float(), nullable=False),
    sa.Column('temperature_bearing_c', sa.Float(), nullable=False),
    sa.Column('temperature_casing_c', sa.Float(), nullable=False),
    sa.Column('pressure_suction_psi', sa.Float(), nullable=False),
    sa.Column('pressure_discharge_psi', sa.Float(), nullable=False),
    sa.Column('motor_current_amps', sa.Float(), nullable=False),
    sa.Column('motor_voltage_v', sa.Float(), nullable=False),
    sa.Column('rul_hours', sa.Integer(), nullable=False),
    sa.Column('failure_risk_7_day', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['master.pump.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_pump_telemetry_pump_id'), 'pump_telemetry', ['pump_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_pump_telemetry_tenant_id'), 'pump_telemetry', ['tenant_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_pump_telemetry_timestamp'), 'pump_telemetry', ['timestamp'], unique=False, schema='bronze')
    op.create_table('pump_features',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('vibration_axial_mm_s', sa.Float(), nullable=False),
    sa.Column('temperature_bearing_c', sa.Float(), nullable=False),
    sa.Column('pressure_discharge_psi', sa.Float(), nullable=False),
    sa.Column('motor_current_amps', sa.Float(), nullable=False),
    sa.Column('vibration_axial_rolling_avg', sa.Float(), nullable=False),
    sa.Column('vibration_axial_rolling_std', sa.Float(), nullable=True),
    sa.Column('temperature_bearing_rolling_avg', sa.Float(), nullable=False),
    sa.Column('temperature_bearing_rolling_max', sa.Float(), nullable=False),
    sa.Column('pressure_discharge_rolling_avg', sa.Float(), nullable=False),
    sa.Column('rul_hours', sa.Integer(), nullable=False),
    sa.Column('failure_risk_7_day', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['master.pump.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gold'
    )
    op.create_index(op.f('ix_gold_pump_features_pump_id'), 'pump_features', ['pump_id'], unique=False, schema='gold')
    op.create_index(op.f('ix_gold_pump_features_tenant_id'), 'pump_features', ['tenant_id'], unique=False, schema='gold')
    op.create_index(op.f('ix_gold_pump_features_timestamp'), 'pump_features', ['timestamp'], unique=False, schema='gold')
    op.create_table('alert',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('status', sa.Enum('TRIGGERED', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['master.pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['master.station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_alert_pump_id'), 'alert', ['pump_id'], unique=False, schema='master')
    op.create_index(op.f('ix_master_alert_station_id'), 'alert', ['station_id'], unique=False, schema='master')
    op.create_index(op.f('ix_master_alert_tenant_id'), 'alert', ['tenant_id'], unique=False, schema='master')
    op.create_table('feature_attribution',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('shap_values', sa.JSON(), nullable=False),
    sa.Column('top_component', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['master.pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_feature_attribution_computed_at'), 'feature_attribution', ['computed_at'], unique=False, schema='master')
    op.create_index(op.f('ix_master_feature_attribution_pump_id'), 'feature_attribution', ['pump_id'], unique=False, schema='master')
    op.create_index(op.f('ix_master_feature_attribution_tenant_id'), 'feature_attribution', ['tenant_id'], unique=False, schema='master')
    op.create_table('health_deviation_record',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pressure_residual', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('health_deviation_index', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['master.pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_health_deviation_record_computed_at'), 'health_deviation_record', ['computed_at'], unique=False, schema='master')
    op.create_index(op.f('ix_master_health_deviation_record_pump_id'), 'health_deviation_record', ['pump_id'], unique=False, schema='master')
    op.create_index(op.f('ix_master_health_deviation_record_tenant_id'), 'health_deviation_record', ['tenant_id'], unique=False, schema='master')
    op.create_table('prediction_result',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_class', sa.String(length=50), nullable=True),
    sa.Column('risk_score_7d', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['master.pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_prediction_result_computed_at'), 'prediction_result', ['computed_at'], unique=False, schema='master')
    op.create_index(op.f('ix_master_prediction_result_pump_id'), 'prediction_result', ['pump_id'], unique=False, schema='master')
    op.create_index(op.f('ix_master_prediction_result_tenant_id'), 'prediction_result', ['tenant_id'], unique=False, schema='master')
    op.create_table('rul_estimate',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remaining_useful_life_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confidence_lower_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confidence_upper_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mc_dropout_samples', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['master.pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_rul_estimate_computed_at'), 'rul_estimate', ['computed_at'], unique=False, schema='master')
    op.create_index(op.f('ix_master_rul_estimate_pump_id'), 'rul_estimate', ['pump_id'], unique=False, schema='master')
    op.create_index(op.f('ix_master_rul_estimate_tenant_id'), 'rul_estimate', ['tenant_id'], unique=False, schema='master')
    op.create_table('work_order',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='work_order_status'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'ALERT', 'SCHEDULE', name='work_order_source'), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['master.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['master.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pump_id'], ['master.pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['master.station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_work_order_pump_id'), 'work_order', ['pump_id'], unique=False, schema='master')
    op.create_index(op.f('ix_master_work_order_station_id'), 'work_order', ['station_id'], unique=False, schema='master')
    op.create_index(op.f('ix_master_work_order_tenant_id'), 'work_order', ['tenant_id'], unique=False, schema='master')
    op.create_table('sensor_reading',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('vibration_axial_mm_s', sa.Float(), nullable=False),
    sa.Column('vibration_radial_mm_s', sa.Float(), nullable=False),
    sa.Column('temperature_bearing_c', sa.Float(), nullable=False),
    sa.Column('temperature_casing_c', sa.Float(), nullable=False),
    sa.Column('pressure_suction_psi', sa.Float(), nullable=False),
    sa.Column('pressure_discharge_psi', sa.Float(), nullable=False),
    sa.Column('motor_current_amps', sa.Float(), nullable=False),
    sa.Column('motor_voltage_v', sa.Float(), nullable=False),
    sa.Column('rul_hours', sa.Integer(), nullable=False),
    sa.Column('failure_risk_7_day', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['master.pump.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='silver'
    )
    op.create_index(op.f('ix_silver_sensor_reading_pump_id'), 'sensor_reading', ['pump_id'], unique=False, schema='silver')
    op.create_index(op.f('ix_silver_sensor_reading_tenant_id'), 'sensor_reading', ['tenant_id'], unique=False, schema='silver')
    op.create_index(op.f('ix_silver_sensor_reading_timestamp'), 'sensor_reading', ['timestamp'], unique=False, schema='silver')
    op.create_table('scheduled_maintenance',
    sa.Column('pump_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='schedule_status'), nullable=False),
    sa.Column('created_from', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['master.pump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['master.station.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['master.tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['master.work_order.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_scheduled_maintenance_pump_id'), 'scheduled_maintenance', ['pump_id'], unique=False, schema='master')
    op.create_index(op.f('ix_master_scheduled_maintenance_station_id'), 'scheduled_maintenance', ['station_id'], unique=False, schema='master')
    op.create_index(op.f('ix_master_scheduled_maintenance_tenant_id'), 'scheduled_maintenance', ['tenant_id'], unique=False, schema='master')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_scheduled_maintenance_tenant_id'), table_name='scheduled_maintenance', schema='master')
    op.drop_index(op.f('ix_master_scheduled_maintenance_station_id'), table_name='scheduled_maintenance', schema='master')
    op.drop_index(op.f('ix_master_scheduled_maintenance_pump_id'), table_name='scheduled_maintenance', schema='master')
    op.drop_table('scheduled_maintenance', schema='master')
    op.drop_index(op.f('ix_silver_sensor_reading_timestamp'), table_name='sensor_reading', schema='silver')
    op.drop_index(op.f('ix_silver_sensor_reading_tenant_id'), table_name='sensor_reading', schema='silver')
    op.drop_index(op.f('ix_silver_sensor_reading_pump_id'), table_name='sensor_reading', schema='silver')
    op.drop_table('sensor_reading', schema='silver')
    op.drop_index(op.f('ix_master_work_order_tenant_id'), table_name='work_order', schema='master')
    op.drop_index(op.f('ix_master_work_order_station_id'), table_name='work_order', schema='master')
    op.drop_index(op.f('ix_master_work_order_pump_id'), table_name='work_order', schema='master')
    op.drop_table('work_order', schema='master')
    op.drop_index(op.f('ix_master_rul_estimate_tenant_id'), table_name='rul_estimate', schema='master')
    op.drop_index(op.f('ix_master_rul_estimate_pump_id'), table_name='rul_estimate', schema='master')
    op.drop_index(op.f('ix_master_rul_estimate_computed_at'), table_name='rul_estimate', schema='master')
    op.drop_table('rul_estimate', schema='master')
    op.drop_index(op.f('ix_master_prediction_result_tenant_id'), table_name='prediction_result', schema='master')
    op.drop_index(op.f('ix_master_prediction_result_pump_id'), table_name='prediction_result', schema='master')
    op.drop_index(op.f('ix_master_prediction_result_computed_at'), table_name='prediction_result', schema='master')
    op.drop_table('prediction_result', schema='master')
    op.drop_index(op.f('ix_master_health_deviation_record_tenant_id'), table_name='health_deviation_record', schema='master')
    op.drop_index(op.f('ix_master_health_deviation_record_pump_id'), table_name='health_deviation_record', schema='master')
    op.drop_index(op.f('ix_master_health_deviation_record_computed_at'), table_name='health_deviation_record', schema='master')
    op.drop_table('health_deviation_record', schema='master')
    op.drop_index(op.f('ix_master_feature_attribution_tenant_id'), table_name='feature_attribution', schema='master')
    op.drop_index(op.f('ix_master_feature_attribution_pump_id'), table_name='feature_attribution', schema='master')
    op.drop_index(op.f('ix_master_feature_attribution_computed_at'), table_name='feature_attribution', schema='master')
    op.drop_table('feature_attribution', schema='master')
    op.drop_index(op.f('ix_master_alert_tenant_id'), table_name='alert', schema='master')
    op.drop_index(op.f('ix_master_alert_station_id'), table_name='alert', schema='master')
    op.drop_index(op.f('ix_master_alert_pump_id'), table_name='alert', schema='master')
    op.drop_table('alert', schema='master')
    op.drop_index(op.f('ix_gold_pump_features_timestamp'), table_name='pump_features', schema='gold')
    op.drop_index(op.f('ix_gold_pump_features_tenant_id'), table_name='pump_features', schema='gold')
    op.drop_index(op.f('ix_gold_pump_features_pump_id'), table_name='pump_features', schema='gold')
    op.drop_table('pump_features', schema='gold')
    op.drop_index(op.f('ix_bronze_pump_telemetry_timestamp'), table_name='pump_telemetry', schema='bronze')
    op.drop_index(op.f('ix_bronze_pump_telemetry_tenant_id'), table_name='pump_telemetry', schema='bronze')
    op.drop_index(op.f('ix_bronze_pump_telemetry_pump_id'), table_name='pump_telemetry', schema='bronze')
    op.drop_table('pump_telemetry', schema='bronze')
    op.drop_index(op.f('ix_silver_weather_reading_timestamp'), table_name='weather_reading', schema='silver')
    op.drop_index(op.f('ix_silver_weather_reading_tenant_id'), table_name='weather_reading', schema='silver')
    op.drop_index(op.f('ix_silver_weather_reading_station_id'), table_name='weather_reading', schema='silver')
    op.drop_table('weather_reading', schema='silver')
    op.drop_index(op.f('ix_silver_regional_risk_score_timestamp'), table_name='regional_risk_score', schema='silver')
    op.drop_index(op.f('ix_silver_regional_risk_score_tenant_id'), table_name='regional_risk_score', schema='silver')
    op.drop_index(op.f('ix_silver_regional_risk_score_station_id'), table_name='regional_risk_score', schema='silver')
    op.drop_table('regional_risk_score', schema='silver')
    op.drop_index(op.f('ix_master_pump_tenant_id'), table_name='pump', schema='master')
    op.drop_index(op.f('ix_master_pump_tag_number'), table_name='pump', schema='master')
    op.drop_index(op.f('ix_master_pump_station_id'), table_name='pump', schema='master')
    op.drop_table('pump', schema='master')
    op.drop_index(op.f('ix_bronze_weather_api_timestamp'), table_name='weather_api', schema='bronze')
    op.drop_index(op.f('ix_bronze_weather_api_tenant_id'), table_name='weather_api', schema='bronze')
    op.drop_index(op.f('ix_bronze_weather_api_station_id'), table_name='weather_api', schema='bronze')
    op.drop_table('weather_api', schema='bronze')
    op.drop_index(op.f('ix_bronze_regional_risk_timestamp'), table_name='regional_risk', schema='bronze')
    op.drop_index(op.f('ix_bronze_regional_risk_tenant_id'), table_name='regional_risk', schema='bronze')
    op.drop_index(op.f('ix_bronze_regional_risk_station_id'), table_name='regional_risk', schema='bronze')
    op.drop_table('regional_risk', schema='bronze')
    op.drop_index(op.f('ix_master_user_tenant_id'), table_name='user', schema='master')
    op.drop_index(op.f('ix_master_user_email'), table_name='user', schema='master')
    op.drop_table('user', schema='master')
    op.drop_index(op.f('ix_master_station_tenant_id'), table_name='station', schema='master')
    op.drop_index(op.f('ix_master_station_code'), table_name='station', schema='master')
    op.drop_table('station', schema='master')
    op.drop_index(op.f('ix_master_model_metric_tenant_id'), table_name='model_metric', schema='master')
    op.drop_index(op.f('ix_master_model_metric_model_name'), table_name='model_metric', schema='master')
    op.drop_index(op.f('ix_master_model_metric_evaluated_at'), table_name='model_metric', schema='master')
    op.drop_table('model_metric', schema='master')
    op.drop_index(op.f('ix_master_tenant_slug'), table_name='tenant', schema='master')
    op.drop_table('tenant', schema='master')
    # ### end Alembic commands ###
